language: node_js
node_js:
  - "4.4"
before_install:
  - npm install -g npm@3.10
install:
  - npm install
  - npm install react@$REACT_VERSION react-addons-css-transition-group@$REACT_VERSION react-addons-test-utils@$REACT_VERSION react-dom@$REACT_VERSION
env:
  global:
    - CXX=g++-4.8
  matrix:
    - REACT_VERSION=0.14
    - REACT_VERSION=15.0
    - REACT_VERSION=15.4
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
