language: node_js
node_js:
  - "4.4"
before_install:
  - npm install -g npm@3.10
install:
  - npm install
  - ./install_react.sh
env:
  global:
    - CXX=g++-4.8
  matrix:
    - REACT_VERSION=15.0
    - REACT_VERSION=15.1
    - REACT_VERSION=15.2
    - REACT_VERSION=15.3
    - REACT_VERSION=15.4
    - REACT_VERSION=15.5
    - REACT_VERSION=15.6
    - REACT_VERSION=16.0
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
